name: Docker release

on:
  push:
    branches:
      - master
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Configure QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build docker images and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm,linux/arm/v6
          tags: |
            ferferga/selfhosted-mail-forwarding:latest
            ghcr.io/ferferga/selfhosted-mail-forwarding:latest
